version: '3'

services:
  jenkin_test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development    
    ports:
      - 5000:80

  postgres:
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jenkin_test